name: Test
on:
  push:


jobs:
  test:
    name: Build mdBook
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Setup mdBook
        uses: peaceiris/actions-mdbook@v2
        with:
          mdbook-version: 'latest'
      - run: mdbook build
